name: Android CI

on: [push]

jobs:
  Wrapper_validation:
    name: "Gradlew wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: ${{ github.workspace }}/owncloudApp/build
      - name: Upload debug/release build
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: builds
          path: ${{ github.workspace }}/owncloudApp/build/outputs/apk
  Espresso_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android Emulator test
        uses: ReactiveCircus/android-emulator-runner@v2.11.0
        with:
          api-level: 28
          disable-animations: true
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: owncloudApp-Espresso-test-report
          path: ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/*
