name: Android CI

on: [push]

jobs:
  Build and test native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: owncloudApp/build/reports
      - name: Upload debug/release build
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: debug/release build
          path: /home/schabi/Projects/owncloud-android/owncloudApp/build/outputs/apk
  Test with Espresso:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android Emulator test
        uses: ReactiveCircus/android-emulator-runner@v2.8.0
        with:
          api-level: 28
          disable-animations: true
          arch: x86_64
          profile: Nexus 6
          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew cAT
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: owncloudApp-Espresso-test-report
          path: ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/*
